name: Build thumbnail-generator

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: buildjet-2vcpu-ubuntu-2204

    permissions:
      contents: read
      packages: write
      id-token: write  # This is required for requesting the JWT


    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/thumbnail-generator:latest
          ghcr.io/${{ github.repository_owner }}/thumbnail-generator:${{ github.sha }}
          ghcr.io/${{ github.repository_owner }}/thumbnail-generator:${{ github.run_number }}
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
